# Generated by Django 6.0.2 on 2026-03-19 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('allowed_roles', models.JSONField()),
                ('metadata', models.JSONField()),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='tenants.branch')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('action_type', models.CharField(choices=[('email', 'E-posta'), ('whataspp', 'Whatsapp'), ('webhook', 'Webhook'), ('sms', 'SMS')])),
                ('order', models.PositiveIntegerField()),
                ('on_failure', models.CharField(choices=[('stop', 'Durdur'), ('continue', 'Devam Et'), ('retry', 'Yeniden dene')])),
                ('config', models.JSONField()),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='automations.automation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('eq', 'Eşittir'), ('neq', 'Eşit Değildir'), ('gt', 'Büyüktür'), ('lt', 'Küçüktür'), ('contains', 'İçerir'), ('in', 'Listede')])),
                ('logical_operator', models.CharField(choices=[('and', 'Ve'), ('or', 'Veya')], default='and', max_length=3)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='automations.automation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failure', 'Başarısız'), ('pending', 'Bekliyor'), ('skipped', 'Atlandı')])),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_context', models.JSONField()),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('scheduled', 'Zamanlanmış'), ('manual', 'Manuel'), ('webhook', 'Webhook'), ('signal', 'Sinyal')])),
                ('config', models.JSONField()),
                ('initial_data', models.JSONField(null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='automations.automation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
