# Generated by Django 6.0.2 on 2026-03-24 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationaction',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_actions', to='channels.channel'),
        ),
    ]
