# Generated by Django 6.0.2 on 2026-03-25 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automationaction_channel'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-posta'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('webhook', 'Webhook'), ('sms', 'SMS')]),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('raw_text', models.TextField(max_length=4096)),
                ('fields', models.JSONField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('channel_type', models.CharField(choices=[('email', 'E-posta'), ('whatsapp', 'Whatsapp'), ('instagram', 'Instagram'), ('sms', 'SMS')])),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.branch')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
